version: 0.2

run-as: aws-codebuild

env:
  shell: /bin/sh

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  # steps:
  build:
    commands:
      - npm run build
