version: 0.2

env:
  shell: /bin/sh

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  # steps:
  build:
    commands:
      - echo "start build"
      - npm run build
      - echo "end Build"
  post_build:
    commands:
      - echo "start post_build"
      - echo "end post_build"
artifacts:
  files:
    - "**/*"
  base-directory: build
